#!/bin/bash

BUILDPATH="$BUILDROOT/work/data"
if [ ! -d "$BUILDPATH" ]; then mkdir $BUILDPATH; fi

if [ ! -d "$BUILDROOT/release/data" ]; then mkdir $BUILDROOT/release/data; fi
if [ ! -d "$BUILDROOT/release/data/roms" ]; then mkdir $BUILDROOT/release/data/roms; fi

if [ "$PIKE" != "" ]; then
	# =======================================================
	# Do some checks
	# =======================================================
	if [ "$AS02" != "" ]; then
		if [ "$CC" != "" ]; then
			# =======================================================
			# Should we build romfixer.c?
			# =======================================================
			if [ "$BUILDPATH/romfixer" -ot "data/src/roms/test/romfixer.c" ]; then
				rm -f $BUILDPATH/romfixer
				rm -f $BUILDPATH/test.bin

				echo "$CC $CFLAGS -o $BUILDPATH/romfixer data/src/roms/test/romfixer.c"
				$CC $CFLAGS -o $BUILDPATH/romfixer data/src/roms/test/romfixer.c
				if [ "$?" != 0 ]; then
					echo "ERROR: romfixer.c failed to compile"
					exit 1
				fi
			fi

			# =======================================================
			# Do some checks
			# =======================================================
			if [ "$BUILDPATH/test.bin" -ot "data/src/roms/test/test.s" ]; then
				rm -f $BUILDPATH/test.bin

				echo "$AS02 -x -z -q -l -o$BUILDPATH/test.bin data/src/roms/test/test.s"
				$AS02 -x -z -q -l -o$BUILDPATH/test.bin data/src/roms/test/test.s

				# Remove some files we don't want or need
				rm -f data/src/roms/test/test.lst

				# Did we succeed?
				if [ "$?" != 0 ]; then
					echo "ERROR: Failed to build test ROM"
					exit 1
				fi
			fi

			if [ "$BUILDROOT/release/data/roms/option/test.bin" -ot "$BUILDPATH/test.bin" ]; then
				if [ ! -d "$BUILDROOT/release/data/roms/option" ]; then mkdir $BUILDROOT/release/data/roms/option; fi

				echo cp $BUILDPATH/test.bin $BUILDROOT/release/data/roms/option/
				cp $BUILDPATH/test.bin $BUILDROOT/release/data/roms/option/
			fi
		fi
	fi
fi

# Copy firmware
echo "Installing firmware ROMs..."
cp -r data/bin/roms/firmware $BUILDROOT/release/data/roms/ || exit 1

#cp data/src/addresses.txt $BUILDROOT/release/data/
#cp -r data/src/addresses $BUILDROOT/release/data/

# Copy binary files
echo "Installing fonts..."
cp -r data/bin/fonts ${BUILDROOT}/release/data/ || exit 1

echo "Installing UI assets..."
cp -r data/bin/ui ${BUILDROOT}/release/data/ || exit 1

# Ensure the target folder is read/write
chmod -R u+rw $BUILDROOT/release/data/
