#!/bin/bash

BUILDPATH="$BUILDROOT/work/data"
if [ ! -d "$BUILDPATH" ]; then mkdir $BUILDPATH; fi

if [ ! -d "$BUILDROOT/release/data" ]; then mkdir $BUILDROOT/release/data; fi
if [ ! -d "$BUILDROOT/release/data/roms" ]; then mkdir $BUILDROOT/release/data/roms; fi

if [ "$PIKE" != "" ]; then
	# =======================================================
	# Do some checks
	# =======================================================
	if [ "$AS02" != "" ]; then
		if [ "$CC" != "" ]; then
			# =======================================================
			# Should we build romfixer.c?
			# =======================================================
			if [ "$BUILDPATH/romfixer" -ot "data/src/roms/test/romfixer.c" ]; then
				rm -f $BUILDPATH/romfixer
				rm -f $BUILDPATH/test.bin
				
				echo "$HOST_CC $CFLAGS -o $BUILDPATH/romfixer data/src/roms/test/romfixer.c"
				$HOST_CC $CFLAGS -o $BUILDPATH/romfixer data/src/roms/test/romfixer.c
				if [ "$?" != 0 ]; then
					echo "ERROR: romfixer.c failed to compile"
					exit 1
				fi
			fi
			
			# =======================================================
			# Do some checks
			# =======================================================
			if [ "$BUILDPATH/test.bin" -ot "data/src/roms/test/test.s" ]; then
				rm -f $BUILDPATH/test.bin
				
				echo "$AS02 -x -z -q -l -o$BUILDPATH/test.bin data/src/roms/test/test.s"
				$AS02 -x -z -q -l -o$BUILDPATH/test.bin data/src/roms/test/test.s
				
				# Remove some files we don't want or need
				rm -f data/src/roms/test/test.lst
				
				# Did we succeed?
				if [ "$?" != 0 ]; then
					echo "ERROR: Failed to build test ROM"
					exit 1
				fi
				
				echo "$BUILDPATH/romfixer $BUILDPATH/test.bin $BUILDPATH/rom3.bin 0"
				$BUILDPATH/romfixer $BUILDPATH/test.bin $BUILDPATH/rom3.bin 0
				
				echo "$BUILDPATH/romfixer $BUILDPATH/test.bin $BUILDPATH/rom2.bin 8192"
				$BUILDPATH/romfixer $BUILDPATH/test.bin $BUILDPATH/rom2.bin 8192
				
				echo "$BUILDPATH/romfixer $BUILDPATH/test.bin $BUILDPATH/rom1.bin 16384"
				$BUILDPATH/romfixer $BUILDPATH/test.bin $BUILDPATH/rom1.bin 16384
				
				echo "$BUILDPATH/romfixer $BUILDPATH/test.bin $BUILDPATH/rom0.bin 24576"
				$BUILDPATH/romfixer $BUILDPATH/test.bin $BUILDPATH/rom0.bin 24576
			fi
			
			if [ "$BUILDROOT/release/data/roms/test/rom0.bin" -ot "$BUILDPATH/rom0.bin" ]; then
				if [ ! -d "$BUILDROOT/release/data/roms/test" ]; then mkdir $BUILDROOT/release/data/roms/test; fi
				
				echo cp $BUILDPATH/rom{0,1,2,3}.bin $BUILDROOT/release/data/roms/test/
				cp $BUILDPATH/rom{0,1,2,3}.bin $BUILDROOT/release/data/roms/test/
			fi
		fi
	fi
fi

if [ -d "data/src/roms/firmware" ]; then cp -r data/src/roms/firmware $BUILDROOT/release/data/roms/; fi
#cp data/src/addresses.txt $BUILDROOT/release/data/
#cp -r data/src/addresses $BUILDROOT/release/data/

chmod -R u+rw $BUILDROOT/release/data/
